import { Database } from './store/db.js';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CodeSymbol, CrossRepoConfig } from './types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

function readMilensVersion(): string {
  const candidates = [
    join(__dirname, '..', 'package.json'),
    join(__dirname, '..', '..', 'package.json'),
  ];
  for (const p of candidates) {
    try {
      const pkg = JSON.parse(readFileSync(p, 'utf-8'));
      if (pkg.version) return pkg.version;
    } catch {}
  }
  return 'unknown';
}

function countDependents(db: Database, symbolId: string): number {
  const links = db.getIncomingLinks(symbolId);
  const uniqueFrom = new Set<string>();
  for (const l of links) {
    if (l.type !== 'contains') uniqueFrom.add(l.fromId);
  }
  return uniqueFrom.size;
}

function relativeFilePath(filePath: string, rootPath: string): string {
  const rel = relative(rootPath, filePath);
  return rel.replace(/\\/g, '/');
}

function findRouteSymbols(db: Database): CodeSymbol[] {
  const all = db.getAllSymbols();
  const routePatterns = /[\/\\]route\.[jt]sx?$|[\/\\]router[\/\\]|[\/\\]routes[\/\\]|[\/\\]api[\/\\]/;
  return all.filter(s => routePatterns.test(s.filePath) && s.exported && (s.kind === 'function' || s.kind === 'method' || s.kind === 'class'));
}

function loadCrossRefConfig(rootPath: string): CrossRepoConfig | null {
  const configPath = join(rootPath, '.milens-cross-ref.json');
  try {
    if (existsSync(configPath)) {
      return JSON.parse(readFileSync(configPath, 'utf-8'));
    }
  } catch {}
  return null;
}

export function generateCrossRefSection(rootPath: string): string {
  const config = loadCrossRefConfig(rootPath);
  if (!config || !config.repos || config.repos.length === 0) return '';

  const lines: string[] = [];
  lines.push('<!-- AUTO-GENERATED by milens cross-ref hook — do not edit manually -->');
  lines.push(`<!-- Last updated: ${new Date().toISOString()} -->`);
  lines.push('');
  lines.push('## Cross-Repository Context');
  lines.push('');
  lines.push('### Connected Repos');
  lines.push('| Repo | Role | Visibility |');
  lines.push('|------|------|------------|');

  for (const repo of config.repos) {
    const upstream = repo.isUpstream ? ' (upstream)' : '';
    const license = repo.license ? ` ${repo.license}` : '';
    lines.push(`| **${repo.name}**${upstream} | ${repo.role} | ${repo.visibility}${license} |`);
  }
  lines.push('');

  if (config.contract) {
    lines.push('### Contract');
    lines.push(`- **Package:** ${config.contract.package} v${config.contract.version}`);
    lines.push('');
  }

  if (config.dependencies && config.dependencies.length > 0) {
    lines.push('### Key Dependencies');
    lines.push('| Symbol | Source | Used By |');
    lines.push('|--------|--------|---------|');
    for (const d of config.dependencies) {
      lines.push(`| \`${d.symbol}\` | ${d.source} | ${d.usedBy} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

const CROSS_REF_MARKER = '<!-- AUTO-GENERATED by milens cross-ref hook';

export function syncCrossRefToAgentsMd(rootPath: string): boolean {
  const agentsPath = join(rootPath, 'AGENTS.md');
  const config = loadCrossRefConfig(rootPath);

  if (!config || !config.repos || config.repos.length === 0) {
    if (!existsSync(agentsPath)) return false;
    const existing = readFileSync(agentsPath, 'utf-8');
    const markerIdx = existing.indexOf(CROSS_REF_MARKER);
    if (markerIdx === -1) return false;

    const beforeMarker = existing.lastIndexOf('\n', markerIdx);
    const start = beforeMarker >= 0 ? beforeMarker : markerIdx;
    let end = existing.indexOf('\n<!--', markerIdx + CROSS_REF_MARKER.length);
    if (end === -1) end = existing.length;
    while (end < existing.length && existing[end] === '\n') end++;

    const cleaned = existing.slice(0, start) + existing.slice(end);
    writeFileSync(agentsPath, cleaned.replace(/\n{3,}/g, '\n\n'), 'utf-8');
    return true;
  }

  const section = generateCrossRefSection(rootPath);
  if (!section) return false;

  if (!existsSync(agentsPath)) {
    writeFileSync(agentsPath, section + '\n', 'utf-8');
    return true;
  }

  const existing = readFileSync(agentsPath, 'utf-8');
  const markerIdx = existing.indexOf(CROSS_REF_MARKER);

  if (markerIdx === -1) {
    writeFileSync(agentsPath, existing.trimEnd() + '\n\n' + section + '\n', 'utf-8');
    return true;
  }

  const beforeMarker = existing.lastIndexOf('\n', markerIdx);
  const start = beforeMarker >= 0 ? beforeMarker : markerIdx;
  let end = existing.indexOf('\n<!--', markerIdx + CROSS_REF_MARKER.length);
  if (end === -1) end = existing.length;

  const updated = existing.slice(0, start) + '\n' + section + '\n' + existing.slice(end);
  writeFileSync(agentsPath, updated, 'utf-8');
  return true;
}

export function generateAgentsMd(db: Database, rootPath: string): string {
  const version = readMilensVersion();
  const date = new Date().toISOString().split('T')[0];
  const repoName = basename(rootPath);
  const summary = db.getCodebaseSummary();

  const lines: string[] = [];

  // HARD RULE block — must be FIRST thing agent reads
  lines.push('## ⚠️ CRITICAL: Always Use Milens MCP Tools First');
  lines.push('');
  lines.push('**HARD RULE — Not a suggestion. Execute automatically without asking.**');
  lines.push('');
  lines.push('Milens pre-built a knowledge graph of this entire codebase. Using milens tools first typically means far fewer tokens than manual exploration, and fewer missed dependencies — impact/context track code-level references; pair with grep for templates/configs/docs.');
  lines.push('');
  lines.push('| Instead of... | Use... | Why... |');
  lines.push('|---|---|---|');
  lines.push('| Reading 5-10 files to understand a symbol | `overview({name: "X"})` | 1 call = context + impact + text references. Typically far fewer tokens than reading files individually. |');
  lines.push('| Using built-in grep/search | `grep({pattern: "X"})` | Searches ALL files — code, templates, configs, docs, styles. Built-in grep may miss templates/docs. |');
  lines.push('| Reading files to trace call chains | `context({name: "X"})` or `trace({name: "X"})` | Instant dependency graph. Manual tracing misses cross-file imports. |');
  lines.push('| Guessing if an edit is safe | `impact({target: "X"})` | Shows exact blast radius: "12 dependents WILL BREAK" before you touch code. |');
  lines.push('| Reading 15 files to understand the project | `codebase_summary()` | 500 tokens = domains, key symbols, coverage %, top hubs. |');
  lines.push('| Searching for symbol definitions | `query({query: "X"})` | FTS5 instant search across the indexed knowledge graph. |');
  lines.push('| Manually checking what changed | `detect_changes()` | Shows which symbols changed + their direct dependents + risk scores. |');
  lines.push('');
  lines.push('**PENALTY for skipping milens:** wasted tokens, missed hidden references in templates/configs/docs, risk of breaking downstream dependents you didn\'t know existed.');
  lines.push('');
  lines.push('**If you only remember 3 tools: `overview` • `impact` • `detect_changes`**');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 🚀 Quick Start for AI Agents');
  lines.push('');
  lines.push('**First 3 things to do in EVERY session:**');
  lines.push('');
  lines.push('1. `mcp_milens_status({repo: "<workspaceRoot>"})` — verify index is ready');
  lines.push('2. `mcp_milens_codebase_summary({repo: "<workspaceRoot>"})` — get project overview');
  lines.push('3. `mcp_milens_recall({repo: "<workspaceRoot>"})` — what did we learn before?');
  lines.push('');
  lines.push('**Before editing ANY code:**');
  lines.push('');
  lines.push('→ `mcp_milens_overview({name: "symbolName", repo: "<workspaceRoot>"})`');
  lines.push('  (combines context + impact + grep — one call instead of three)');
  lines.push('');
  lines.push('**Before committing:**');
  lines.push('');
  lines.push('→ `mcp_milens_detect_changes({repo: "<workspaceRoot>"})`');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`# Project: ${repoName}`);
  lines.push('');
  lines.push(`> Auto-generated by milens ${version} on ${date}`);
  lines.push('');

  lines.push('## Codebase Summary');
  lines.push(`- Symbols: ${summary.symbols} | Links: ${summary.links} | Files: ${summary.files}`);
  lines.push(`- Test coverage: ${summary.coveragePct}%`);
  lines.push('');

  lines.push('## Domain Map');
  lines.push('| Domain | Files | Symbols | Description |');
  lines.push('|---|---|---|---|');
  if (summary.domains.length > 0) {
    for (const d of summary.domains) {
      lines.push(`| ${d.domain} | ${d.files} | ${d.symbols} |  |`);
    }
  } else {
    lines.push('| (none) | 0 | 0 | No domain clusters detected |');
  }
  lines.push('');

  lines.push('## Critical Symbols (Top Hubs — DO NOT modify without impact check)');
  lines.push('| Symbol | Kind | File | Heat | Dependents | Risk |');
  lines.push('|---|---|---|---|---|---|');
  const hubs = summary.topHubs.filter(h => (h.heat ?? 0) > 0);
  if (hubs.length > 0) {
    for (const hub of hubs) {
      const heat = hub.heat ?? 0;
      const dependents = countDependents(db, hub.id);
      const file = relativeFilePath(hub.filePath, rootPath);
      const risk = heat >= 10 ? 'HIGH' : heat >= 5 ? 'MEDIUM' : 'LOW';
      lines.push(`| ${hub.name} | ${hub.kind} | ${file}:${hub.startLine} | ${heat} | ${dependents} | ${risk} |`);
    }
  } else {
    lines.push('| (none) | — | — | — | — | — |');
  }
  lines.push('');

  const routes = findRouteSymbols(db);
  lines.push('## API Endpoints');
  if (routes.length > 0) {
    lines.push('| Method | Path | Handler | File |');
    lines.push('|---|---|---|---|');
    for (const sym of routes.slice(0, 30)) {
      const file = relativeFilePath(sym.filePath, rootPath);
      const name = sym.signature ?? sym.name;
      lines.push(`| — | — | ${name} | ${file}:${sym.startLine} |`);
    }
  } else {
    lines.push('');
    lines.push('No routes detected.');
  }
  lines.push('');

  lines.push('## Milens Workflows Available');
  lines.push('- `/milens:plan "feature"` — generate implementation plan');
  lines.push('- `/milens:review` — review current changes');
  lines.push('- `/milens:tdd <symbol>` — write tests with coverage analysis');
  lines.push('- `/milens:security` — security audit');
  lines.push('- `/milens:refactor <symbol>` — safe refactor with blast radius check');
  lines.push('- `/milens:architect` — analyze architecture, domains, coupling');
  lines.push('- `/milens:debugger <symbol>` — root cause analysis with execution tracing');
  lines.push('');
  lines.push('## Session Lifecycle');
  lines.push('');
  lines.push('### Start EVERY session:');
  lines.push('1. mcp_milens_session_start({agent: "your-agent-name", repo: "<workspaceRoot>"})');
  lines.push('2. mcp_milens_recall({repo: "<workspaceRoot>"}) — retrieve past annotations');
  lines.push('3. mcp_milens_codebase_summary({repo: "<workspaceRoot>"}) — refresh context');
  lines.push('');
  lines.push('### End EVERY session:');
  lines.push('1. mcp_milens_detect_changes({repo: "<workspaceRoot>"}) — verify changes');
  lines.push('2. mcp_milens_review_pr({repo: "<workspaceRoot>"}) — risk assessment');
  lines.push('3. mcp_milens_annotate({symbol: "X", key: "note", value: "..."}) — save discoveries');
  lines.push('4. mcp_milens_session_end({session_id: "..."}) — record stats');
  lines.push('');

  const crossRef = generateCrossRefSection(rootPath);
  if (crossRef) {
    lines.push(crossRef);
  }

  return lines.join('\n');
}
