import { Database } from './store/db.js';
import { readFileSync } from 'node:fs';
import { join, relative, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CodeSymbol } from './types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

function readMilensVersion(): string {
  const candidates = [
    join(__dirname, '..', 'package.json'),
    join(__dirname, '..', '..', 'package.json'),
  ];
  for (const p of candidates) {
    try {
      const pkg = JSON.parse(readFileSync(p, 'utf-8'));
      if (pkg.version) return pkg.version;
    } catch {}
  }
  return 'unknown';
}

function countDependents(db: Database, symbolId: string): number {
  const links = db.getIncomingLinks(symbolId);
  const uniqueFrom = new Set<string>();
  for (const l of links) {
    if (l.type !== 'contains') uniqueFrom.add(l.fromId);
  }
  return uniqueFrom.size;
}

function relativeFilePath(filePath: string, rootPath: string): string {
  const rel = relative(rootPath, filePath);
  return rel.replace(/\\/g, '/');
}

function findRouteSymbols(db: Database): CodeSymbol[] {
  const all = db.getAllSymbols();
  const routePatterns = /[\/\\]route\.[jt]sx?$|[\/\\]router[\/\\]|[\/\\]routes[\/\\]|[\/\\]api[\/\\]/;
  return all.filter(s => routePatterns.test(s.filePath) && s.exported && (s.kind === 'function' || s.kind === 'method' || s.kind === 'class'));
}

export function generateAgentsMd(db: Database, rootPath: string): string {
  const version = readMilensVersion();
  const date = new Date().toISOString().split('T')[0];
  const repoName = basename(rootPath);
  const summary = db.getCodebaseSummary();

  const lines: string[] = [];

  lines.push(`# Project: ${repoName}`);
  lines.push('');
  lines.push(`> Auto-generated by milens ${version} on ${date}`);
  lines.push('');

  lines.push('## Codebase Summary');
  lines.push(`- Symbols: ${summary.symbols} | Links: ${summary.links} | Files: ${summary.files}`);
  lines.push(`- Test coverage: ${summary.coveragePct}%`);
  lines.push('');

  lines.push('## Domain Map');
  lines.push('| Domain | Files | Symbols | Description |');
  lines.push('|---|---|---|---|');
  if (summary.domains.length > 0) {
    for (const d of summary.domains) {
      lines.push(`| ${d.domain} | ${d.files} | ${d.symbols} |  |`);
    }
  } else {
    lines.push('| (none) | 0 | 0 | No domain clusters detected |');
  }
  lines.push('');

  lines.push('## Critical Symbols (Top Hubs — DO NOT modify without impact check)');
  lines.push('| Symbol | Kind | File | Heat | Dependents | Risk |');
  lines.push('|---|---|---|---|---|---|');
  const hubs = summary.topHubs.filter(h => (h.heat ?? 0) > 0);
  if (hubs.length > 0) {
    for (const hub of hubs) {
      const heat = hub.heat ?? 0;
      const dependents = countDependents(db, hub.id);
      const file = relativeFilePath(hub.filePath, rootPath);
      const risk = heat >= 10 ? 'HIGH' : heat >= 5 ? 'MEDIUM' : 'LOW';
      lines.push(`| ${hub.name} | ${hub.kind} | ${file}:${hub.startLine} | ${heat} | ${dependents} | ${risk} |`);
    }
  } else {
    lines.push('| (none) | — | — | — | — | — |');
  }
  lines.push('');

  const routes = findRouteSymbols(db);
  lines.push('## API Endpoints');
  if (routes.length > 0) {
    lines.push('| Method | Path | Handler | File |');
    lines.push('|---|---|---|---|');
    for (const sym of routes.slice(0, 30)) {
      const file = relativeFilePath(sym.filePath, rootPath);
      const name = sym.signature ?? sym.name;
      lines.push(`| — | — | ${name} | ${file}:${sym.startLine} |`);
    }
  } else {
    lines.push('');
    lines.push('No routes detected.');
  }
  lines.push('');

  lines.push('## Milens Workflows Available');
  lines.push('- `/milens:plan "feature"` — generate implementation plan');
  lines.push('- `/milens:review` — review current changes');
  lines.push('- `/milens:tdd <symbol>` — write tests with coverage analysis');
  lines.push('- `/milens:security` — security audit');
  lines.push('- `/milens:refactor <symbol>` — safe refactor with blast radius check');
  lines.push('');

  lines.push('## Session Startup');
  lines.push('When starting work, call:');
  lines.push('1. session_start({agent: "your-agent-name"})');
  lines.push('2. recall({}) — retrieve past annotations');
  lines.push('3. codebase_summary({}) — refresh context');
  lines.push('');

  return lines.join('\n');
}
